LudusCMS.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using LudusCMS.Model;
using LudusCMS.Model.ViewModels;
using LudusCMS.Web.Infrastructure.Alerts;

namespace LudusCMS.Web.Controllers
{
    public class BlogController : CommonController
    {
        //
        // GET: /Blogs/
        public ActionResult Index()
        {
            //Get All Blogs
            var model = UnitOfWork.Repository<Blog>().GetBy(includes: new List<System.Linq.Expressions.Expression<Func<Blog, object>>> { x => x.Tags, y => y.Categories, z => z.Department });
            model = model.OrderByDescending(m => m.Created);

            return View(model);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return Redirect("Index");
            }

            //Get a specific Blog By Id (primary key)
            var blog = UnitOfWork.Repository<Blog>().GetBy(filter: x => x.Id == (Int32)id, includes: new List<System.Linq.Expressions.Expression<Func<Blog, object>>> { x => x.Tags, y => y.Categories, z => z.Department }).First();

            if (blog == null)
            {
                return RedirectToAction("Index");
            }


            var filteredCategories = UnitOfWork.Repository<Category>().GetAll();
            var filteredTags = UnitOfWork.Repository<Tag>().GetAll();


            var model = new BlogViewModel
            {
                Blog = blog,
                Departments = UnitOfWork.Repository<Department>().GetAll(),
                Tags = new MultiSelectList(filteredTags, "Id", "Name"),
                Categories = new MultiSelectList(filteredCategories, "Id", "Name"),
            };

            return View(model);
        }
        #region Only Partial Views
        public ActionResult PVGetBlogs(int? page, int? pageSize)
        {
            var pageNumber = page ?? 1;
            var itemsPerPage = pageSize ?? 10;

            var model = UnitOfWork.Repository<Blog>().GetBy(orderBy: m => m.OrderByDescending(p => p.Updated));

            var pagedModel = model.ToPagedList(pageNumber, itemsPerPage);

            return PartialView("_ListBlogs", pagedModel);
        }

        [HttpGet]
        public ActionResult CreateCommentForBlog(int blogId, int? userId, string ajaxUpdateTargetId, int? parentCommentId)
        {
            var model = new CreateCommentForBlogViewModel
            {
                Comment = new LudusCMS.Model.Comment(),
                BlogId = blogId,
                UserId = userId ?? null,
                AJAXUpdateTargetId = ajaxUpdateTargetId,
                ParentCommentId = parentCommentId ?? null
            };

            return PartialView("_CreateCommentForBlog", model);
        }

        [HttpPost]
        public ActionResult CreateCommentForBlog(CreateCommentForBlogViewModel model)
        {
            if (!ModelState.IsValid)
                throw new Exception("Model is not valid!");

            var modelToSave = new Comment()
            {
                Content = model.Comment.Content,
                BlogId = model.BlogId,
                UserId = model.UserId,
                ParentCommentId = model.ParentCommentId
            };

            UnitOfWork.Repository<Comment>().Insert(modelToSave);
            var result = UnitOfWork.SaveChanges();

            return GetCommentsByBlogAsPagedList(model.BlogId, model.UserId, 1, 10);
        }

        public ActionResult GetCommentsByBlogAsPagedList(int blogId, int? userId, int? page, int? pageSize)
        {
            int pageNumber = page ?? 1;
            int itemsPerPage = pageSize ?? 10;

            var model = UnitOfWork.Repository<Comment>().GetBy(
                    filter: f => f.BlogId == blogId,
                    orderBy: m => m.OrderByDescending(p => p.Id)
                );

            var pagedModel = model.ToPagedList(pageNumber, itemsPerPage);

            var viewModel = new CommentsByBlogViewModel()
            {
                Comments = pagedModel,
                BlogId = blogId,
                UserId = userId
            };

            var users = UnitOfWork.Repository<ApplicationUser>().GetAll();

            ViewBag.Users = users;

            return PartialView("_PagedListCommentsByBlog", viewModel);
        }
        #endregion
    }
}

LudusCMS.Web/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LudusCMS.Model;
using LudusCMS.Model.ViewModels;
using Microsoft.AspNet.Identity;

namespace LudusCMS.Web.Controllers
{
    public class EventController : CommonController
    {
        //
        // GET: /Events/
        public ActionResult Index()
        {
            try
            {
                int id = Convert.ToInt16(User.Identity.GetUserId());

                var user = UnitOfWork.Repository<ApplicationUser>().GetById(id);

                var events = UnitOfWork.Repository<Event>().GetAll();

                

                var categories = UnitOfWork.Repository<EventCategory>().GetAll();

               
                ViewBag.Events = events;
                ViewBag.Categories = categories;



                if (user.ChildId == null)
                {
                    var userdepartment = UnitOfWork.Repository<Department>().GetBy(filter: x => x.Id == user.DepartmentId).First();
                    var userclass = UnitOfWork.Repository<Class>().GetBy(filter: x => x.Id == user.ClassId).First();
                    var model = UnitOfWork.Repository<Event>().GetBy(filter: x => x.DepartmentId == userdepartment.Id && x.ClassId == userclass.Id || x.DepartmentId == userdepartment.Id && x.ClassId == null || x.DepartmentId == null );
                   
                    model = model.OrderByDescending(m => m.Start_Date);

                    return View(model);
                }
                else
                {
                    var child = UnitOfWork.Repository<ApplicationUser>().GetBy(filter: x => x.Id == user.ChildId).First();
                    var userdepartment = UnitOfWork.Repository<Department>().GetBy(filter: x => x.Id == child.DepartmentId).First();
                    var userclass = UnitOfWork.Repository<Class>().GetBy(filter: x => x.Id == child.ClassId).First();

                    var model = UnitOfWork.Repository<Event>().GetBy(filter: x => x.DepartmentId == userdepartment.Id && x.ClassId == userclass.Id || x.DepartmentId == userdepartment.Id && x.ClassId == null || x.DepartmentId == null);
                    model = model.OrderByDescending(m => m.Start_Date);

                    return View(model);
                }



            }
            catch
            {
                return RedirectToAction("Error", "Course");
            }



        }
    }
}

LudusCMS.Web/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using LudusCMS.Model;
using LudusCMS.Model.ViewModels;
using LudusCMS.Web.Infrastructure.Alerts;
using Microsoft.AspNet.Identity;

namespace LudusCMS.Web.Controllers
{
    public class MessageController :CommonController
    {
        //Postvak In 
        public ActionResult Index()
        {
            //Get All Messages
            int id = Convert.ToInt16(User.Identity.GetUserId());
            var model = UnitOfWork.Repository<Message>().GetBy(filter: x => x.ReceiverId == id);
            model = model.OrderByDescending(m => m.Created);

            return View(model);
        }


        public ActionResult Details(Int16? id)
        {
            ViewBag.Users = UnitOfWork.Repository<ApplicationUser>().GetAll();
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var model = new MessageViewModel
            {
                Message = UnitOfWork.Repository<Message>().GetById(id),
                Receivers = UnitOfWork.Repository<ApplicationUser>().GetAll()
                
            };

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Backoffice/Meesage/Create
        public ActionResult Create()
        {
            var model = new MessageViewModel
            {
                Message = new Message()
                {

                    SenderId = Convert.ToInt16(User.Identity.GetUserId())
                },
                Receivers = UnitOfWork.Repository<ApplicationUser>().GetAll()
            };

            return View(model);
        }

        // POST: Backoffice/Message/Create
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(MessageViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Message is not valid!");

                var message = model.Message;

                UnitOfWork.Repository<Message>().Insert(message);
                int result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                var viewModel = new MessageViewModel
                {
                    Message = model.Message,
                    Receivers = UnitOfWork.Repository<ApplicationUser>().GetAll()
                };

                return View(viewModel);
            }
        }


        public ActionResult Autocomplete(string term)
        {
        try
        {
            var model = UnitOfWork.Repository<ApplicationUser>().GetAll()  // your data here
            .Where(p => p.Email.StartsWith(term))
            .Take(5)
            .Select(p => new
            {
                // jQuery UI needs the label property to function 
                label = p.Email.Trim(),
                value = p.Id
                
            });

        // Json returns [{"label":value}]
            return Json(model.Select(m => new
            {
                id = m.value,
                value = m.value,
                label = m.label,
            }), JsonRequestBehavior.AllowGet);
        }
        catch (Exception ex)
        {
        
        return Json("{'ex':'Exception'}");
        }
    }

        //Postvack Out
        public ActionResult IndexSended()
        {
            //Get All Messages
            int id = Convert.ToInt16(User.Identity.GetUserId());
            var model = UnitOfWork.Repository<Message>().GetBy(filter: x => x.SenderId == id);
            model = model.OrderByDescending(m => m.Created);

            return View(model);
        }

       
        public ActionResult SendedDetails(Int16? id)
        {
            ViewBag.Users = UnitOfWork.Repository<ApplicationUser>().GetAll();
            if (id == null)
            {
                return RedirectToAction("IndexSended");
            }

            var model = new MessageViewModel
            {
                Message = UnitOfWork.Repository<Message>().GetById(id),
                Receivers = UnitOfWork.Repository<ApplicationUser>().GetAll()

            };

            if (model == null)
            {
                return RedirectToAction("IndexSended");
            }

            return View(model);
        }
        public ActionResult Reply(Int16? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var originalModel = UnitOfWork.Repository<Message>().GetById(id);
            var model = new MessageViewModel
            {
                Message = new Message{
                    SenderId= Convert.ToInt16(User.Identity.GetUserId()),
                    ReceiverId = originalModel.SenderId,
                    Title = "Re:" + originalModel.Title

                },
                Receivers = UnitOfWork.Repository<ApplicationUser>().GetAll()
            };

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Reply(MessageViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Message is not valid!");

                var message = model.Message;

                UnitOfWork.Repository<Message>().Insert(message);
                int result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                var viewModel = new MessageViewModel
                {
                    Message = model.Message,
                    Receivers = UnitOfWork.Repository<ApplicationUser>().GetAll()
                };

                return View(viewModel);
            }
        }
       


        #region Only Partial Views
        //Postvak In
        public ActionResult PVGetMessages(int? page, int? pageSize)
        {
            int id = Convert.ToInt16(User.Identity.GetUserId());
            var pageNumber = page ?? 1;
            var itemsPerPage = pageSize ?? 15;

            var model = UnitOfWork.Repository<Message>().GetBy(filter: x => x.ReceiverId == id);
            model = model.OrderByDescending(m => m.Updated);

            var pagedModel = model.ToPagedList(pageNumber, itemsPerPage);

            return PartialView("_ListMessages", pagedModel);
        }

        //Postvak Out

        public ActionResult PVGetSendedMessages(int? page, int? pageSize)
        {
            int id = Convert.ToInt16(User.Identity.GetUserId());
            var pageNumber = page ?? 1;
            var itemsPerPage = pageSize ?? 15;

            var model = UnitOfWork.Repository<Message>().GetBy(filter: x => x.SenderId == id);
            model = model.OrderByDescending(m => m.Updated);

            var pagedModel = model.ToPagedList(pageNumber, itemsPerPage);

            return PartialView("_ListSendedMessages", pagedModel);
        }
        #endregion

        
    }
}

LudusCMS.Web/Views/Shared/_Alert.cshtml
<div class="row" id="alert-container">
</div>

LudusCMS.Web/Views/Shared/_Footer.cshtml
<div id="footer">
    <p>&copy; Gemaakt door Florian Van Damme en Robby van den Broecke in opdracht van Arteveldehogeschool 2014 - 2015</p>
</div>

LudusCMS.Web/Views/Shared/_Header.cshtml
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Ludus</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Student") || User.IsInRole("Parent"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Blog")" title="Blog">Blog</a>
                    </li>
                }
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Student") || User.IsInRole("Parent"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Message")" title="Berichten">Berichten</a>
                    </li>
                }
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Student") || User.IsInRole("Parent"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Event")" title="Agenda">Agenda</a>
                    </li>
                }
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Student") || User.IsInRole("Parent"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Calendar")" title="Kalender">Kalender</a>
                    </li>
                }
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Student") || User.IsInRole("Parent"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Schedule")" title="Lessenrooster">Lessenrooster</a>
                    </li>
                }
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Student") || User.IsInRole("Parent"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Course")" title="Cursussen">Cursussen</a>
                    </li>
                }
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Student") || User.IsInRole("Parent"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Reportcard")" title="Rapporten">Rapporten</a>
                    </li>
                }
                @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator"))
                {
                    <li>
                        <a href="@Url.Action("Index", "Home", new { area = "Backoffice" })" title="Beheer">Beheer</a>
                    </li>
                }
            </ul>
           <ul class="nav navbar-nav navbar-right">          
                    @if (Request.IsAuthenticated)
                    {
                        <li><a>Hallo, @User.Identity.Name</a></li>
                        <li>
                        <ul id="profile-info-ul">
                            <li><a href="@Url.Action("Profile", "Account")" title=""><span class="glyphicon glyphicon-user"></span>Profiel</a></li>
                            <li>
                                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <a href="javascript:document.getElementById('logoutForm').submit()"><span class="glyphicon glyphicon-off"></span>Uitloggen</a>
                                }
                            </li>
                        </ul>
                    </li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Login", "Account")" title="Inloggen">Inloggen</a></li>
                    }
                </ul>
</div><!--/.nav-collapse -->
    </div>
</nav>

LudusCMS.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<!-- [if lt IE 7]><html dir="ltr" lang="nl-be" class="no-js lt-ie7"><![endif]-->
<!-- [if lt IE 8]><html dir="ltr" lang="nl-be" class="no-js lt-ie8"><![endif]-->
<!-- [if lt IE 9]><html dir="ltr" lang="nl-be" class="no-js lt-ie9"><![endif]-->
<!-- [if lt IE 10]><html dir="ltr" lang="nl-be" class="no-js lt-ie10"><![endif]-->
<!-- [if (gt IE 9)|!(IE)]><!-->
<html dir="ltr" lang="nl-be" class="no-js" prefix="og: http://ogp.me/ns#">
<!--<![endif]-->
<head>
    @* CHARACTER ENCODING *@
    <meta charset="UTF-8">
    @* LATEST VERSION OF RENDERING ENGINE *@
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    @* MOST IMPORTANT SEO FRIENDLY TAG *@
    <title>@ViewBag.Title</title>
    @* OTHER IMPORTANT SEO TAGS *@
    <meta name="description" content="@ViewBag.Description">
    <meta name="keywords" content="@ViewBag.Keywords">
    <meta name="author" content="@ViewBag.Author">
    <meta name="copyright" content="Copyright 2003-@DateTime.Now.Year Arteveldehogeschool. Alle rechten voorbehouden.">
    @* HUMANS AUTHORS TEXT FILE *@
    <link type="text/plain" rel="author" href="~/humans.txt">
    @* FAVICON AND TOUCHICONS ex: http://demosthenes.info/blog/467/Creating-MultiResolution-Favicons-For-Web-Pages-With-GIMP *@
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/content/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/content/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/content/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/content/icons/apple-touch-icon-57-precomposed.png">
    <link href="~/content/icons/favicon.ico" rel="icon" type="image/x-icon">
    <link href="~/content/icons/favicon.ico" rel="shortcut icon" type="image/x-icon">
    @* MOBILE VIEWPORT *@
    <meta name="viewport" content="width=device-width">
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")

    @Styles.Render("~/Content/themes/base/css")


</head>
<body>
    @* Header Partial *@
    @Html.Partial("_Header")
    
    @* Main Content *@

            @* Alert Partial*@
            @Html.Partial("_Alert")

            @* Render the body of the view *@
            @RenderBody()



    
    @* Modal Popup Partial *@
    @Html.Partial("_Modal")

    @* Footer Partial *@
    @Html.Partial("_Footer")

    @* jQuery *@
    @Scripts.Render("~/bundles/jquery")

   
  
   
    @Scripts.Render("~/bundles/jqueryui")


    @* AlertManager TempData JS *@
    @using LudusCMS.Web.Infrastructure.Alerts
    @if (TempData.GetAlerts().Any())
    {
        <script>
            (function () {
                @foreach (var alert in TempData.GetAlerts())
			            {
				            <text>
                window.AlertManager.showAlert('@alert.Type', '@alert.Message.Replace("'", "\\'")');
                </text>
			            }
            })();
        </script>
    }

    

    @* jQuery
    @Scripts.Render("~/bundles/jquery")
    *@
    @* Bootstrap *@
    @Scripts.Render("~/bundles/bootstrap")

    @* jQuery Validate *@
    @Scripts.Render("~/bundles/jqueryval")

    @* Custom scripts specified in the views*@
    @RenderSection("scripts", required: false)
   
</body>
</html>

LudusCMS.Web/Views/Shared/_LayoutAccount.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* Main Content *@
<img src="~/Content/images/Banner.png" alt="Ludus" id="banner" class="hidden-sm hidden-xs" />
<div class="wrapper" id="main-wrapper">
    <div class="container">
        <main id="main" role="main">

            <header id="main-header" class="clearfix">
                <h1>@ViewBag.Title</h1>
            </header>

            @* Render the body of the view *@
            @RenderBody()
        </main>
    </div>
</div>


@* Render the scripts again
    @section scripts{
        @RenderSection("scripts", required: false)
    }

*@

LudusCMS.Web/Views/Shared/_LayoutHome.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@RenderSection("banners", required: false)

@* Main Content *@
<div class="wrapper" id="main-wrapper">
    <div class="container">
        <main id="main" role="main" class="col col-xs-12 col-sm-12 col-md-12 col-lg-12">

            <header id="main-header" class="clearfix hidden">
                <h1>@ViewBag.Title <small>@ViewBag.SubTitle</small></h1>
            </header>

            @* Render the body of the view *@
            @RenderBody()
        </main>
    </div>
</div>


@* Render the scripts again
    @section scripts{
        @RenderSection("scripts", required: false)
    }
*@

LudusCMS.Web/Views/Shared/_LayoutPage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="wrapper" id="main-wrapper">
    <div class="container">
        <div class="row">
            @* Main Content *@
            <main id="main" role="main" class="col col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <header>
                    <h1>@ViewBag.Title</h1>
                </header>
                @* Render the body of the view *@
                @RenderBody()
            </main>
        </div>
    </div>
</div>


@section scripts{
    @RenderSection("scripts", required: false)
}

LudusCMS.Web/Views/Shared/_Sidebar.cshtml
@* Sidebar, on the left in the backoffice *@
@if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Teacher") || User.IsInRole("Parent"))
            {

        <ul class="nav navbar-nav side-nav">

            <li class="active">
                <a href="@Url.Action("Index", "Home")" title="">
                    <span class="glyphicon glyphicon-home"></span>
                    <span class="label-menu">Dashboard</span>
                </a>
            </li>

            @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Teacher") || User.IsInRole("Parent"))
            {
                <li class="submenu">
                    <a href="#" title="">
                        <span class="fa fa-rocket"></span>
                        <span class="label-menu">Agenda</span>
                        <span class="pull-right arrow"></span>
                    </a>
                    <ul class="slider-down">
                        <li>
                            <a href="@Url.Action("Index", "Event")" title="Agenda">
                                <span class="label-menu">Bekijk Agenda</span>
                            </a>
                        </li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Teacher") || User.IsInRole("Parent"))
            {
                <li class="submenu">
                    <a href="#" title="">
                        <span class="fa fa-calendar"></span>
                        <span class="label-menu">Lessenrooster</span>
                        <span class="pull-right arrow"></span>
                    </a>
                    <ul class="slider-down">
                        <li>
                            <a href="@Url.Action("Index", "Schedule")" title="Lessenrooster">
                                <span class="label-menu"> Bekijk Lessenrooster</span>
                            </a>
                        </li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Teacher"))
            {
                <li class="submenu">
                    <a href="#" title="">
                        <span class="fa fa-newspaper-o"></span>
                        <span class="label-menu">Blogs</span>
                        <span class="pull-right arrow"></span>
                    </a>
                    <ul class="slider-down">
                        <li>
                            <a href="@Url.Action("Index", "Blog")" title="All blogs">
                                <span class="label-menu">Alle Blogs</span>
                            </a>
                        </li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Teacher") || User.IsInRole("Parent"))
            {
                <li class="submenu">
                    <a href="#" title="">
                        <span class="fa fa-book"></span>
                        <span class="label-menu">Cursussen</span>
                        <span class="pull-right arrow"></span>
                    </a>
                    <ul class="slider-down">
                        <li>
                            <a href="@Url.Action("Index", "Course")" title="">
                                <span class="label-menu">Alle Cursussen</span>
                            </a>
                        </li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator") || User.IsInRole("Teacher") || User.IsInRole("Parent"))
            {
                <li class="submenu">
                    <a href="#" title="">
                        <span class="fa fa-line-chart"></span>
                        <span class="label-menu">Rapporten</span>
                        <span class="pull-right arrow"></span>
                    </a>
                    <ul class="slider-down">
                        <li>
                            <a href="@Url.Action("Index", "Reportcard")" title="">
                                <span class="label-menu">Alle Rapporten</span>
                            </a>
                        </li>
                    </ul>
                </li>
            }
            @if (User.IsInRole("Teacher") || User.IsInRole("Admin") || User.IsInRole("Classtitular") || User.IsInRole("secretary") || User.IsInRole("Principal") || User.IsInRole("Schoolcoordinator"))
            {


                <li class="submenu">
                    <a href="#" title="">
                        <span class="fa fa-lock"></span>
                        <span class="label-menu">Backoffice</span>
                        <span class="pull-right arrow"></span>
                    </a>
                    <ul class="slider-down">
                        <li>
                            <a href="@Url.Action("Index", "Home", new { area = "Backoffice" })" title="">
                                <span class="label-menu">Naar Backoffice</span>
                            </a>
                        </li>
                    </ul>
                </li>

            }
        </ul>
                


            }