LudusCMS.Web/Areas/Backoffice/Controllers/EventcategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LudusCMS.Model;
using LudusCMS.Web.Areas.Backoffice.Controllers;
using LudusCMS.Web.Infrastructure.Alerts;

namespace LudusCMS.Web.Areas.Backoffice.Controllers
{
    public class EventcategoryController : CommonController
    {
        // GET: Backoffice/Eventcategory
        public ActionResult Index()
        {
            var model = UnitOfWork.Repository<EventCategory>().GetAll();
            model = model.OrderByDescending(m => m.Created);

            if (this.Request.IsAjaxRequest())
            {
                return PartialView("_ListPartial", model);
            }

            return View(model);
        }

        // GET: Backoffice/Eventcategory/Create
        public ActionResult Create()
        {
            var model = new EventCategory();//Create empty model

            return View(model);
        }

        // POST: Backoffice/Eventcategory/Create
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(EventCategory model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Eventcategory is not valid!");


                UnitOfWork.Repository<EventCategory>().Insert(model);
                int result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        public ActionResult Edit(Int16? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            //Get a specific Course By Id (primary key)
            var model = UnitOfWork.Repository<EventCategory>().GetById(id);

            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Edit(Course model)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("Eventcategory is not valid!");

                var originalModel = UnitOfWork.Repository<EventCategory>().GetById(model.Id);

                if (originalModel == null)
                    throw new Exception("Eventcategory do not exist!");

                originalModel.Name = model.Name;


                UnitOfWork.Repository<EventCategory>().Update(originalModel);
                var result = UnitOfWork.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var model = UnitOfWork.Repository<EventCategory>().GetById(id);

                if (model == null)
                    throw new Exception("EventCategory does not exist!");

                UnitOfWork.Repository<EventCategory>().Delete(id);
                int result = UnitOfWork.SaveChanges();

                var msg = CreateMessage(ControllerActionType.Delete, "eventcategory", model.Id);

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 1, id = model.Id, message = msg });
                }
                else
                {
                    return RedirectToAction("Index", "EventCategory").WithSuccess(msg);
                }

            }
            catch (Exception ex)
            {
                var msg = CreateMessage(ControllerActionType.Delete, "eventcategory", id, ex);

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 0, id = id, message = msg });
                }
                else
                {
                    return RedirectToAction("Index", "EventCategory").WithError(msg);
                }
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult VirtualDelete(int id)
        {
            try
            {
                var model = UnitOfWork.Repository<EventCategory>().GetById(id);

                if (model == null)
                    throw new Exception("EventCategory does not exist!");

                UnitOfWork.Repository<EventCategory>().VirtualDelete(id);
                int result = UnitOfWork.SaveChanges();

                var msg = CreateMessage(ControllerActionType.VirtualDelete, "eventcategory", model.Id);

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 1, id = model.Id, message = msg });
                }
                else
                {
                    return RedirectToAction("Index", "EventCategory").WithSuccess(msg);
                }

            }
            catch (Exception ex)
            {
                var msg = CreateMessage(ControllerActionType.VirtualDelete, "eventcategory", id, ex);

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 0, id = id, message = msg });
                }
                else
                {
                    return RedirectToAction("Index", "EventCategory").WithError(msg);
                }
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult VirtualUnDelete(int id)
        {
            try
            {
                var model = UnitOfWork.Repository<EventCategory>().GetById(id);

                if (model == null)
                    throw new Exception("EventCategory does not exist!");

                UnitOfWork.Repository<EventCategory>().VirtualUnDelete(id);
                int result = UnitOfWork.SaveChanges();

                var msg = CreateMessage(ControllerActionType.VirtualUnDelete, "eventcategory", model.Id);

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 1, id = model.Id, message = msg });
                }
                else
                {
                    return RedirectToAction("Index", "EventCategory").WithSuccess(msg);
                }

            }
            catch (Exception ex)
            {
                var msg = CreateMessage(ControllerActionType.VirtualUnDelete, "eventcategory", id, ex);

                if (this.Request.IsAjaxRequest())
                {
                    return Json(new { state = 0, id = id, message = msg });
                }
                else
                {
                    return RedirectToAction("Index", "EventCategory").WithError(msg);
                }
            }
        }
    }
}

LudusCMS.Web/Areas/Backoffice/Views/Eventcategory/Create.cshtml
@model LudusCMS.Model.EventCategory
@{
   
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}




<div class="row">
    <section class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Create a new eventcategory
            </div>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <fieldset>
                        <legend class="hidden">eventcategory</legend>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Name)
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        </div>
                        

                        <input type="submit" value="Create" class="btn btn-default" />
                        @Html.ActionLink("Back to the list", "Index", new { }, new { @class = "btn btn-primairy" })
                    </fieldset>
                }
            </div>
        </div>
    </section>
</div>

LudusCMS.Web/Areas/Backoffice/Views/Eventcategory/Edit.cshtml
@model LudusCMS.Model.EventCategory
@{
   
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <section class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Edit an existing eventcategory
            </div>
            <div class="panel-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <fieldset>
                        <legend class="hidden">eventcategory</legend>
                        @Html.HiddenFor(m => m.Id)
                        <div class="form-group">
                            @Html.LabelFor(m => m.Name)
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        </div>
                        

                     
                        <input type="submit" value="Save" class="btn btn-default" />
                        @Html.ActionLink("Back to the list", "Index", new { }, new { @class = "btn btn-primairy" })
                    </fieldset>
                }
            </div>
        </div>
    </section>
</div>

LudusCMS.Web/Areas/Backoffice/Views/Eventcategory/Index.cshtml
@model IEnumerable<LudusCMS.Model.EventCategory>
@{
    ViewBag.Title = "Event Categories";
    Layout = "~/Areas/Backoffice/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <section class="col-xs-12" id="eventcategories-list">
        @{Html.RenderPartial("_ListPartial", Model);}
    </section>
</div>
@section Scripts {
    <script>
        window.ConfirmManager.registerClickHandlers();
        window.ConfirmManager.registerModalHandlers();
    </script>
}

LudusCMS.Web/Areas/Backoffice/Views/Eventcategory/_ListPartial.cshtml
@model IEnumerable<LudusCMS.Model.EventCategory>
@Html.AntiForgeryToken()
<div class="panel panel-default">
    <div class="panel-heading">
        @Html.ActionLink("Create a new EventCategory", "Create", new { }, new { @class = "btn btn-default" })
    </div>
    <div class="panel-body">
        @if (Model != null && Model.Count() > 0)
        {
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Modified</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var eventcategory in Model)
                        {
                            <tr data-id="eventcategory-@eventcategory.Id" data-title="@eventcategory.Name">
                                <td>@eventcategory.Name</td>
                                <td>@eventcategory.Updated</td>
                                <td>
                                    <a href="@Url.Action("Edit", new { id = @eventcategory.Id })" title="Edit eventcategory: @eventcategory.Name"><i class="fa fa-edit"></i></a>
                                    <a class="confirm-link" href="@Url.Action("Delete", new { id = @eventcategory.Id })" title="Delete eventcategory: @eventcategory.Name" data-id="@eventcategory.Id"  data-cat="eventcatgeory" data-action="delete" data-update-href="@Url.Action("Index", "Eventcategory")" data-update-target="#eventcategories-list"><i class="fa fa-trash"></i></a>
                                    @if (@eventcategory.Deleted != null)
                                    {
                                        <a class="confirm-link" href="@Url.Action("VirtualUnDelete", new { id = @eventcategory.Id })" title="Soft-undelete eventcategory: @eventcategory.Name" data-id="@eventcategory.Id" data-cat="eventcategory" data-action="virtualundelete" data-update-href="@Url.Action("Index", "Eventcategory")" data-update-target="#eventcategories-list"><i class="fa fa-eye-slash"></i></a>
                                    }
                                    else
                                    {
                                        <a class="confirm-link" href="@Url.Action("VirtualDelete", new { id = @eventcategory.Id })" title="Soft-delete eventcategory: @eventcategory.Name data-id="@eventcategory data-cat="eventcategory" data-action="virtualdelete" data-update-href="@Url.Action("Index", "Eventcategory")" data-update-target="#eventcategories-list"><i class="fa fa-eye"></i></a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <p>No Departments in the database!</p>
        }
    </div>
    <div class="panel-footer">
        
    </div>
</div>